language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - "export DISPLAY=:99.0"                                         # Required for graphics
  - "sh -e /etc/init.d/xvfb start"                                 # Required for graphics
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone("https://github.com/codles/MinMaxFilter.jl.git")'
  - julia -e 'Pkg.add("DSP"); Pkg.checkout("DSP")'
  - julia -e 'Pkg.add("SIUnits"); Pkg.checkout("SIUnits")'
  - julia -e 'Pkg.clone("git://github.com/codles/EEG.jl.git")'
  - julia -e 'Pkg.update()'                                       # Required for Tk to work
  - julia -e 'Pkg.build("EEG")'                                   # Required for Tk to work
  - julia -e 'Pkg.test("EEG")'
  - julia --code-coverage ./test/runtests.jl
after_success:
- julia -e 'cd(Pkg.dir("EEG")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
