language: julia
os:
  - linux
julia:
  - release
  # - nightly
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"                                         # Required for graphics
  - "sh -e /etc/init.d/xvfb start"                                 # Required for graphics
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/codles/MinMaxFilter.jl.git")'
  - julia -e 'Pkg.add("DSP"); Pkg.checkout("DSP")'
  - julia -e 'Pkg.add("SIUnits"); Pkg.checkout("SIUnits")'
  # - julia -e 'Pkg.clone("git://github.com/codles/EEG.jl.git")'
  # - julia -e 'Pkg.update()'                                       # Required for Tk to work
  # - julia -e 'Pkg.build("EEG")'                                   # Required for Tk to work
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("EEG"); Pkg.test("EEG"; coverage=true)
after_success:
 - if [ $TRAVIS_JULIA_VERSION = "release" ]; then julia -e 'cd(Pkg.dir("EEG")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
