language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    #- JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone("https://github.com/codles/MinMaxFilter.jl.git")'
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("EEG")'
  - julia --code-coverage ./test/runtests.jl
after_success:
- julia -e 'cd(Pkg.dir("EEG")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
