site_name:           EEG.jl
repo_url:            https://github.com/codles/EEG.jl
site_description:    Process electrophysiological recordings in Julia.
site_author:         Robert Luke
theme:               readthedocs
markdown_extensions: [tables, fenced_code]
pages:
    - ['index.md', 'Introduction']
    - ['manual.md', 'Manual', 'Overview']
    - ['examples/waveforms.md', 'Examples', 'Plotting Waveforms']
    - ['examples/ftest-plot.md', 'Examples', 'Plotting Spectrum and Statistics']
    - ['examples/ASSR.md', 'Examples', 'Auditory Steady State Responses Statistics']
